explore the cleaned data and the preprocessing phase

In [1]:
from src.preprocess import remove_offsets

In [2]:
imu, offsets = remove_offsets()
offsets

file              column
imu_acceleration  x        -0.072248
imu_angular_rate  x         1.076229
                  y        -0.276122
                  z         1.011456
dtype: float64

Since the method we used was to take the average of means of offset during each window so the offset to substract matches our values we set in issues.csv

In [4]:
imu["imu_angular_rate"]

                t_s        _timestamp         x         y         z
0          0.001332  1725799119377875  0.113771  0.076122  0.038544
1          0.005799  1725799119382342  0.133771  0.166122  0.048544
2          0.010266  1725799119386809  0.123771  0.156122  0.018544
3          0.014807  1725799119391350  0.223771 -0.013878  0.078544
4          0.019228  1725799119395771 -0.096229  0.196122  0.078544
...             ...               ...       ...       ...       ...
489824  2206.949995  1725801326326538 -0.166229  0.026122 -0.041456
489825  2206.954010  1725801326330553  0.073771 -0.073878  0.018544
489826  2206.958487  1725801326335030 -0.376229 -0.043878 -0.011456
489827  2206.962945  1725801326339488 -0.246229  0.116122 -0.041456
489828  2206.967405  1725801326343948 -0.046229  0.056122 -0.051456

[489829 rows x 5 columns]

In [5]:
imu["imu_acceleration"]

                t_s        _timestamp         x     y     z
0          0.002541  1725799119379084  0.002248 -0.02 -0.97
1          0.007002  1725799119383545  0.002248 -0.02 -0.97
2          0.011476  1725799119388019  0.002248 -0.02 -0.97
3          0.015953  1725799119392496  0.002248 -0.03 -0.97
4          0.020418  1725799119396961  0.002248 -0.03 -0.97
...             ...               ...       ...   ...   ...
489824  2206.950817  1725801326327360  0.012248 -0.02 -0.99
489825  2206.955222  1725801326331765  0.012248 -0.01 -0.97
489826  2206.962301  1725801326338844 -0.007752 -0.02 -0.95
489827  2206.964155  1725801326340698  0.002248 -0.02 -0.98
489828  2206.968685  1725801326345228  0.002248 -0.02 -0.98

[489829 rows x 5 columns]

imu_acc z is still ~-0.97 at rest