In [4]:
from src.config import PIT_MIN_S, PROC_DATA
import pandas as pd
from src.preprocess import load_processed

In [7]:
df = load_processed()
df

,t_s,hv_power__power,imu_angular_rate__x,imu_angular_rate__y,imu_angular_rate__z,imu_acceleration__x,imu_acceleration__y,imu_acceleration__z,vehicle_position__x,vehicle_position__y,...,pedal_brakes_pressure__front,pedal_brakes_pressure__rear,pedal_throttle__throttle,steer_angle__angle,front_angular_velocity__fl,front_angular_velocity__fr,inv_r_id_a8_n_actual_filt__n_act_filt,inv_l_id_a8_n_actual_filt__n_act_filt,inv_r_id_27_iq_actual__iq_act_filt,inv_l_id_27_iq_actual__iq_act_filt
0,2.188702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.192702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
2,2.196702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
3,2.200702,0.131650,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000
4,2.204702,0.121386,NaN,NaN,NaN,NaN,NaN,NaN,-218.066681,34.317539,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.109383,0.051784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551187,2206.936702,-0.001526,-0.190444,-0.052721,-0.000712,0.002248,-0.020000,-0.983122,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,0.031180,0.000000
551188,2206.940702,-0.001526,-0.146536,-0.043939,-0.070965,0.002248,-0.012936,-0.968809,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.029027,0.000000
551189,2206.944702,-0.001526,-0.082120,-0.236204,-0.053140,0.002248,-0.016021,-0.953979,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000
551190,2206.948702,-0.001526,-0.142615,-0.047344,-0.044080,0.007444,-0.020000,-0.970781,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000
551191,2206.952702,-0.001526,-0.004415,-0.041300,-0.001003,0.012248,-0.015721,-0.981442,-272.358276,38.590065,...,0.0,0.0,0.0,-2.439555,-0.003052,-0.003052,0.0,0.0,-0.074935,0.000000

In [25]:
df.columns

Index(['t_s', 'hv_power__power', 'imu_angular_rate__x', 'imu_angular_rate__y',
       'imu_angular_rate__z', 'imu_acceleration__x', 'imu_acceleration__y',
       'imu_acceleration__z', 'vehicle_position__x', 'vehicle_position__y',
       'vehicle_position__heading', 'vehicle_speed__u', 'vehicle_speed__v',
       'vehicle_curvilinear_coordinates__s',
       'vehicle_curvilinear_coordinates__n', 'pedal_brakes_pressure__front',
       'pedal_brakes_pressure__rear', 'pedal_throttle__throttle',
       'steer_angle__angle', 'front_angular_velocity__fl',
       'front_angular_velocity__fr', 'inv_r_id_a8_n_actual_filt__n_act_filt',
       'inv_l_id_a8_n_actual_filt__n_act_filt',
       'inv_r_id_27_iq_actual__iq_act_filt',
       'inv_l_id_27_iq_actual__iq_act_filt'],
      dtype='str')

In [8]:
df["vehicle_curvilinear_coordinates__s"]

0         790.998673
1         790.998673
2         790.998673
3         790.998673
4         790.998673
             ...
551187    736.999598
551188    736.999598
551189    736.999598
551190    736.999598
551191    736.999598
Name: vehicle_curvilinear_coordinates__s, Length: 551192, dtype: float64

In [10]:
from src.utils import find_standstills
standstills = find_standstills()

In [11]:
standstills

       start_s        end_s  duration_s
0     0.000000    13.002358   13.002358
1    20.790024    54.929918   34.139894
2   161.421000   176.054854   14.633854
3   192.778036   206.897613   14.119577
4   227.119072   242.465951   15.346879
5   977.176868  1157.391011  180.214143
6  1163.760712  1196.196530   32.435818
7  1829.968137  1908.013226   78.045089
8  1920.559415  2206.962362  286.402947

In [19]:
pit_cand = standstills[standstills["duration_s"] >= PIT_MIN_S]
pit_cand

       start_s        end_s  duration_s
5   977.176868  1157.391011  180.214143
7  1829.968137  1908.013226   78.045089
8  1920.559415  2206.962362  286.402947

In [14]:
from src.utils import find_laps
raw_laps = find_laps()

In [15]:
raw_laps

,lap_number,start_s,end_s,lap_time_s,has_stop,has_gap,has_pit,is_out_lap,valid
0,1,61.447598,133.758730,72.311132,False,False,False,False,True
1,2,133.758730,281.465908,147.707178,True,False,False,False,False
2,3,281.465908,348.448507,66.982599,False,False,False,False,True
3,4,348.448507,413.994435,65.545928,False,False,False,False,True
4,5,413.994435,477.396409,63.401974,False,False,False,False,True
5,6,477.396409,539.871968,62.475559,False,False,False,False,True
6,7,539.871968,603.920050,64.048082,False,True,False,False,False
7,8,603.920050,665.375170,61.455120,False,False,False,False,True
8,9,665.375170,726.564443,61.189273,False,True,False,False,False
9,10,726.564443,787.367604,60.803161,False,True,False,False,False
10,11,787.367604,848.838904,61.471300,False,True,False,False,False
11,12,848.838904,910.240131,61.401227,False,False,False,False,True
12,13,910.240131,972.009224,61.769093,False,False,False,False,True
13,14,972.009224,1203.733071,231.723847,True,True,True,True,False
14,15,1203.733071,1270.906110,67.173039,False,False,False,False,True
15,16,1270.906110,1334.621896,63.715786,False,True,False,False,False
16,17,1334.621896,1397.577341,62.955445,False,False,False,False,True
17,18,1397.577341,1459.020535,61.443194,False,False,False,False,True
18,19,1459.020535,1520.200158,61.179623,False,False,False,False,True
19,20,1520.200158,1587.460414,67.260256,False,False,False,False,True
20,21,1587.460414,1649.263642,61.803228,False,True,False,False,False
21,22,1649.263642,1712.916918,63.653276,False,False,False,False,True
22,23,1712.916918,1775.022498,62.105580,False,False,False,False,True

In [18]:
race_start_t = raw_laps["start_s"].iloc[0]
race_end_t = raw_laps["end_s"].iloc[-1]

In [21]:
pits = pit_cand[(pit_cand["start_s"] > race_start_t) & (pit_cand["end_s"] < race_end_t)]

In [22]:
pits

      start_s        end_s  duration_s
5  977.176868  1157.391011  180.214143

In [23]:
for i in range(len(pits)):
    stint_i = i +1
    stints = {
        stint_i : [pits["start_s"].iloc[i], pits["end_s"].iloc[i]]
    }

In [24]:
stints

{1: [np.float64(977.176868), np.float64(1157.391011)]}

In [1]:
from src.segment import find_segment_standstills

In [2]:
std = find_segment_standstills()
std

       start_s        end_s  duration_s
0     2.216702    13.008702      10.792
1    20.776702    54.928702      34.152
2   161.416702   176.068702      14.652
3   192.732702   206.908702      14.176
4   227.108702   242.484702      15.376
5   977.172702  1157.396702     180.224
6  1163.760702  1196.200702      32.440
7  1829.972702  1908.044702      78.072
8  1920.548702  2206.952702     286.404

In [5]:
pits_cand = std[std["duration_s"] >= PIT_MIN_S]
pits_cand

       start_s        end_s  duration_s
5   977.172702  1157.396702     180.224
7  1829.972702  1908.044702      78.072
8  1920.548702  2206.952702     286.404

In [18]:
df = load_processed()

In [27]:
data = df[(~df["front_angular_velocity__fl"].isna()) & (~df["front_angular_velocity__fr"].isna())]

In [29]:
data["front_angular_velocity__fr"]

7        -0.003052
8        -0.003052
9        -0.003052
10       -0.003052
11       -0.003052
            ...
551187   -0.003052
551188   -0.003052
551189   -0.003052
551190   -0.003052
551191   -0.003052
Name: front_angular_velocity__fr, Length: 544294, dtype: float64